AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TypeScript Lambda function example

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 5

Resources:
  TypeScriptFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda.handler
      CodeUri: ./
      Environment:
        Variables:
          BUCKET_NAME: bs-ts
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: arn:aws:s3:::bs-ts
