name: Deploy Step Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Compile TypeScript
      run: npm run build

    - name: Package Lambda functions
      run: |
        cd dist/lambdas
        zip -r multiplyByTwo.zip multiplyByTwo.js ../node_modules
        zip -r checkGreaterThanTen.zip checkGreaterThanTen.js ../node_modules


    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda functions
      run: |
        chmod +x deploy-lambda.sh
        ./deploy-lambda.sh MultiplyByTwoFunction fileb://dist/lambdas/multiplyByTwo.zip multiplyByTwo
        ./deploy-lambda.sh CheckGreaterThanTenFunction fileb://dist/lambdas/checkGreaterThanTen.zip checkGreaterThanTen

    - name: Deploy Step Function
      run: |
        aws stepfunctions update-state-machine --state-machine-arn  arn:aws:states:us-east-1:728900521350:stateMachine:HelloWorld --definition file://src/stateMachineDefinition.json